site_name: Addok
pages:
- index.md
- Installation: install.md
- Tutoriel: tutorial.md
- Configuration: config.md
- Tuning Redis: redis.md
- Plugins: plugins.md
- Import: import.md
- HTTP API: api.md
- Shell: shell.md
- Fabric: fabric.md
- Concepts: concepts.md
- Exemples: examples.md
- FAQ: faq.md
- Changelog: changelog.md
theme: readthedocs
repo_url: https://github.com/etalab/addok
site_description: Moteur de recherche pour les adresses. Seulement les adresses.
