site_name: Addok
pages:
- index.md
- Installation: install.md
- Configuration: config.md
- Tuning de Redis: redis.md
- Plugins: plugins.md
- Import: import.md
- HTTP API: api.md
- Shell: shell.md
- Tutoriel: tutorial.md
- Concepts: concepts.md
- FAQ: faq.md
- Changelog: changelog.md
theme: readthedocs
repo_url: https://github.com/etalab/addok
site_description: Search engine for address. Only address.
